config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :invoice_details
  # resources :invoices
  get 'invoices', to: 'invoices#index'
  get 'invoices/new', to: 'invoices#new', as: 'new_invoices'
  delete 'invoices/:invoice_id', to: 'invoices#destroy'
  post 'invoices', to: 'invoices#create'
  get 'invoices/:invoice_id', to: 'invoices#show', as: 'invoice'
  get 'invoices/:invoice_id/edit', to: 'invoices#edit', as:'edit_invoice'
  patch 'invoices/:invoice_id', to: 'invoices#update', as: 'update_invoices'
  resources :members
  # resources :groups, except: [:destroy]
  get 'groups', to: 'groups#index'
  get '/groups/:group_id', to: 'groups#show', as: 'group'
  get 'groups/:group_id/edit', to: 'groups#edit', as: 'edit_group'
  # PDF出力
  get '/pdf-download/:id', to: 'pdf#download', as: 'pdf_download', :format => 'pdf'
  get 'pdf-show/:id' => 'pdf#show', as: 'pdf_show', :format => 'pdf'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    has_many :invoice_details
    has_many :groups
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
    @invoice_details = @invoice.invoice_details.includes(:invoice).all.order(sort: "asc")
    # @invoice_details = InvoiceDetail.all
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
    @invoice_details = @invoice.invoice_details.includes(:invoice).all.order(sort: "asc")
    @invoice_detail = InvoiceDetail.new
  end

  # POST /invoices or /invoices.json
  def create
    @group = Group.find_by(owner_id: current_user.id)
    @invoice = Invoice.new(invoice_params)

    @invoice.invoice_id = SecureRandom.uuid
    @invoice.group_id = @group.group_id

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to '/groups/' + @group.group_id, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { render :edit, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice = Invoice.find_by(invoice_id: params[:invoice_id])
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find_by(invoice_id: params[:invoice_id])
      # member = Member.find_by(name: “Kei”)
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:title, :company_name, :zip, :pref, :address, :tel, :subtotal, :tax_rate, :tax, :amount, :sub1)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="field">
    <%= form.label :pref %>
    <%= form.text_field :pref %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel %>
  </div>

  <div class="field">
    <%= form.label :subtotal %>
    <%= form.number_field :subtotal %>
  </div>

  <div class="field">
    <%= form.label :tax_rate %>
    <%= form.number_field :tax_rate %>
  </div>

  <div class="field">
    <%= form.label :tax %>
    <%= form.number_field :tax %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :sub1 %>
    <%= form.text_field :sub1 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/index.html.erb
<h1 class="mt-5">Invoices</h1>
<p invoice_id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Company name</th>
      <th>Zip</th>
      <th>Pref</th>
      <th>Address</th>
      <th>Tel</th>
      <th>Subtotal</th>
      <th>Tax rate</th>
      <th>Tax</th>
      <th>Amount</th>
      <th>Sub1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.title %></td>
        <td><%= invoice.company_name %></td>
        <td><%= invoice.zip %></td>
        <td><%= invoice.pref %></td>
        <td><%= invoice.address %></td>
        <td><%= invoice.tel %></td>
        <td><%= invoice.subtotal %></td>
        <td><%= invoice.tax_rate %></td>
        <td><%= invoice.tax %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.sub1 %></td>
        <td>
        <%= link_to 'Show', '/invoices/' + invoice.invoice_id %>
        </td>
        <td><%= link_to 'Edit', '/invoices/' + invoice.invoice_id + '/edit' %></td>
        <td><%= link_to 'Destroy', '/invoices/' + invoice.invoice_id, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Invoice', '/invoices/new' %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>
<%# <div id="form_area" class="field">
    <label for="invoice_sub1">Sub1</label>
    <input type="text" name="invoice[sub1]" id="inputform_0">
  </div>
<input type="button" value="フォーム追加" onclick="addForm()"> %>
<%= link_to 'Back', invoices_path %>

<%# <script>
var i = 1 ;
function addForm() {
    var parent = document.getElementById('form_area');
    let div_start = '.list'
    parent.appendChild(div_start);
    var input_data = document.createElement('input');
    input_data.type = 'text';
    input_data.id = 'inputform_' + i;
    input_data.placeholder = 'フォーム-' + i;
    // var parent = document.getElementById('form_area');
    parent.appendChild(input_data);
    let div_end = 'list'
    parent.appendChild(div_end);
    i++ ;
}
</script> %>

app/views/invoices/pdf.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @invoice.title %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @invoice.company_name %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @invoice.zip %>
</p>

<p>
  <strong>Pref:</strong>
  <%= @invoice.pref %>
</p>

<p>
  <strong>Address:</strong>
  <%= @invoice.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @invoice.tel %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @invoice.subtotal %>
</p>

<p>
  <strong>Tax rate:</strong>
  <%= @invoice.tax_rate %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @invoice.amount %>
</p>

<p>
  <strong>Sub1:</strong>
  <%= @invoice.sub1 %>
</p>

<p>
  <strong>InvoiceDetails:</strong>
  <% @invoice_details.each do |detail| %>
    <p><%= detail.title %></p>
  <% end %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mt-5">InvoiceDetail</h1>

<p>
  <strong>Title:</strong>
  <%= @invoice.title %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @invoice.company_name %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @invoice.zip %>
</p>

<p>
  <strong>Pref:</strong>
  <%= @invoice.pref %>
</p>

<p>
  <strong>Address:</strong>
  <%= @invoice.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @invoice.tel %>
</p>

<p>
  <strong>InvoiceDetails:</strong>
  <% subTotal = 0%>
  <% @invoice_details.each do |detail| %>
    <p>
    <%= detail.title %>：
    <%= detail.quantity %>
    <%= detail.unit %>,
    <%= detail.unit_price.to_s(:delimited) %>
    <% subTotal += detail.unit_price%>
    </p>
  <% end %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= subTotal.to_s(:delimited) %>
</p>

<p>
  <strong>Tax rate:</strong>
  <%= @invoice.tax_rate %>
</p>

<p>
  <strong>Tax:</strong>
  <% if subTotal != 0 %>
    <% tax = subTotal * @invoice.tax_rate / 100 %>
    <%= tax.to_s(:delimited) %>
  <% end %>
</p>

<p>
  <strong>Amount:</strong>
  <% if subTotal != 0 %>
    <% amount = subTotal + tax %>
    <%= amount.to_s(:delimited) %>
  <% end %>
</p>

<p>
  <strong>Sub1:</strong>
  <%= @invoice.sub1 %>
</p>
<p>
<% pdfLink = '/pdf-download/' + @invoice.id.to_s %>
</p>

<%= link_to 'Edit', @invoice.invoice_id + '/edit' %> |
<%= link_to 'Back', invoices_path %> | 
<%= link_to 'PDF', pdfLink %>