config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :invoice_details
  # resources :invoices
  get 'invoices', to: 'invoices#index'
  get 'invoices/new', to: 'invoices#new', as: 'new_invoices'
  delete 'invoices/:invoice_id', to: 'invoices#destroy'
  post 'invoices', to: 'invoices#create'
  get 'invoices/:invoice_id', to: 'invoices#show', as: 'invoice'
  get 'invoices/:invoice_id/edit', to: 'invoices#edit', as:'edit_invoice'
  patch 'invoices/:invoice_id', to: 'invoices#update', as: 'update_invoices'
  resources :members
  # resources :groups, except: [:destroy]
  get 'groups', to: 'groups#index'
  get '/groups/:group_id', to: 'groups#show', as: 'group'
  get 'groups/:group_id/edit', to: 'groups#edit', as: 'edit_group'
  # PDF出力
  get '/pdf-download/:id', to: 'pdf#download', as: 'pdf_download', :format => 'pdf'
  get 'pdf-show/:id' => 'pdf#show', as: 'pdf_show', :format => 'pdf'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :invoices

  validates :name, presence: true
  validates :introduction, presence: true
  # attachment :image, destroy: false
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @groups = Group.all
  end

  def show

    # @group = Group.find(params[:group_id])
    @group = Group.find_by(group_id: params[:group_id])
    @invoices = Invoice.where(group_id: params[:group_id]).order("created_at desc")
    # @invoices = Invoice.where(group_id: params[:group_id]).includes(:group).order("created_at desc")
    # @comments = Comment.where(board_id: params[:id]).includes(:user).order("created_at desc")
    # @invoices = @group.invoices.includes(:group).all.order(sort: "asc")
    # @invoice_details = @invoice.invoice_details.includes(:invoice).all.order(sort: "asc")
    # @invoices = Invoice.all
    # @invoices = Invoice.find_by(id: 1)
  end

  def new
    @group = Group.new
  end

  def create
    # group_params.group_id = SecureRandom.uuid
    @group = Group.new(group_params)
    @group.group_id = SecureRandom.uuid
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:group_id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "group was successfully destroyed." }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>
        <%= render 'form', group: @group %>
  </div>
</div>

app/views/groups/index.html.erb
<h2>Groups</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td></td>
        <td>
          <%= link_to group.name, group_path(group_id: group.group_id) %>
        </td>
        <td><%= group.introduction %></td>
        <td>
          <% if group.owner_id == current_user.id %>
            <%= link_to 'Edit', edit_group_path(group_id: group.group_id), class: "btn btn-sm btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <td>
          <% if @group.name.nil? %>
            <%= @group.name %>
          <% end %>
          </td>
          <td>
          </td>
          <td><%= @group.introduction %></td>
          <td>
            <% if @group.owner_id == current_user.id %>
              <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Company name</th>
      <th>Zip</th>
      <th>Pref</th>
      <th>Address</th>
      <th>Tel</th>
      <th>Subtotal</th>
      <th>Tax rate</th>
      <th>Tax</th>
      <th>Amount</th>
      <th>Sub1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.title %></td>
        <td><%= invoice.company_name %></td>
        <td><%= invoice.zip %></td>
        <td><%= invoice.pref %></td>
        <td><%= invoice.address %></td>
        <td><%= invoice.tel %></td>
        <td><%= invoice.subtotal %></td>
        <td><%= invoice.tax_rate %></td>
        <td><%= invoice.tax %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.sub1 %></td>
        <td>
        <%= link_to 'Show', '/invoices/' + invoice.invoice_id %>
        </td>

        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>