config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  resources :invoice_details
  # resources :invoices
  get 'invoices', to: 'invoices#index'
  get 'invoices/new', to: 'invoices#new', as: 'new_invoices'
  delete 'invoices/:invoice_id', to: 'invoices#destroy'
  post 'invoices', to: 'invoices#create'
  get 'invoices/:invoice_id', to: 'invoices#show', as: 'invoice'
  get 'invoices/:invoice_id/edit', to: 'invoices#edit', as:'edit_invoice'
  patch 'invoices/:invoice_id', to: 'invoices#update', as: 'update_invoices'
  resources :members
  # resources :groups, except: [:destroy]
  get 'groups', to: 'groups#index'
  get '/groups/:group_id', to: 'groups#show', as: 'group'
  get 'groups/:group_id/edit', to: 'groups#edit', as: 'edit_group'
  # PDF出力
  get '/pdf-download/:id', to: 'pdf#download', as: 'pdf_download', :format => 'pdf'
  get 'pdf-show/:id' => 'pdf#show', as: 'pdf_show', :format => 'pdf'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
    belongs_to :invoice
end

app/controllers/invoice_details_controller.rb
class InvoiceDetailsController < ApplicationController
  protect_from_forgery
  before_action :set_invoice_detail, only: %i[ show edit update destroy ]

  # GET /invoice_details or /invoice_details.json
  def index
    @invoice_details = InvoiceDetail.all
  end

  # GET /invoice_details/1 or /invoice_details/1.json
  def show
  end

  # GET /invoice_details/new
  def new
    @invoice_detail = InvoiceDetail.new
  end

  # GET /invoice_details/1/edit
  def edit
  end

  # POST /invoice_details or /invoice_details.json
  def create
    @invoice_detail = InvoiceDetail.new(invoice_detail_params)

    respond_to do |format|
      if @invoice_detail.save
        format.html { redirect_to @invoice_detail, notice: "Invoice detail was successfully created." }
        format.json { render :show, status: :created, location: @invoice_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_details/1 or /invoice_details/1.json
  def update
    respond_to do |format|
      if @invoice_detail.update(invoice_detail_params)
        format.html { render :show, status: :ok, notice: "Invoice detail was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_details/1 or /invoice_details/1.json
  def destroy
    @invoice_detail.destroy
    respond_to do |format|
      format.html { render :show, status: :ok, notice: "Invoice detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_detail
      @invoice_detail = InvoiceDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_detail_params
      params.require(:invoice_detail).permit(:title, :quantity, :unit, :unit_price, :sort, :invoice_id)
    end
end

app/helpers/invoice_details_helper.rb
module InvoiceDetailsHelper
end

app/views/invoice_details/_form.html.erb
<%= form_with(model: invoice_detail, local: true) do |form| %>
  <% if invoice_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_detail.errors.count, "error") %> prohibited this invoice_detail from being saved:</h2>

      <ul>
      <% invoice_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.number_field :unit_price %>
  </div>

  <div class="field">
    <%= form.label :sort %>
    <%= form.number_field :sort %>
  </div>

  <div class="field">
    <%= form.label :invoice_id %>
    <%= form.number_field :invoice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_details/edit.html.erb
<h1>Editing Invoice Detail</h1>

<%= render 'form', invoice_detail: @invoice_detail %>

<%= link_to 'Show', @invoice_detail %> |
<%= link_to 'Back', invoice_details_path %>

app/views/invoice_details/index.html.erb
<h1>Invoice Details</h1>
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Quantity</th>
      <th>Unit</th>
      <th>Unit price</th>
      <th>Sort</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_details.each do |invoice_detail| %>
      <tr>
        <td><%= invoice_detail.title %></td>
        <td><%= invoice_detail.quantity %></td>
        <td><%= invoice_detail.unit %></td>
        <td><%= invoice_detail.unit_price %></td>
        <td><%= invoice_detail.sort %></td>
        <td><%= invoice_detail.invoice_id %></td>
        <td><%= link_to 'Show', invoice_detail %></td>
        <td><%= link_to 'Edit', edit_invoice_detail_path(invoice_detail) %></td>
        <td><%= link_to 'Destroy', invoice_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Detail', new_invoice_detail_path %>

app/views/invoice_details/new.html.erb
<h1>New Invoice Detail</h1>

<%= render 'form', invoice_detail: @invoice_detail %>

<%= link_to 'Back', invoice_details_path %>

app/views/invoice_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @invoice_detail.title %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @invoice_detail.quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @invoice_detail.unit %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @invoice_detail.unit_price %>
</p>

<p>
  <strong>Sort:</strong>
  <%= @invoice_detail.sort %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @invoice_detail.invoice_id %>
</p>

<%= link_to 'Edit', edit_invoice_detail_path(@invoice_detail) %> |
<%= link_to 'Back', invoice_details_path %>